name: Hello Agile

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello from GitHub Actions!"

        # This workflow will trigger on pushes to the 'dev' branch and on pull requests targeting the 'main' branch. It will print a simple message to the console.
        #hiiii